### PR TITLE
add support for Equidistant Cylindrical projection

### PR DESCRIPTION
**Pull request by bakamotokatas**
Hello @Schuch666, I am working on lat-long projection too, so I added this to wrf_raster. I tested the results and it seems to be working fine. You can see the images below.

image
Height variable from wrf_raster

image
WRF Domain from GIS4WRF

### CODE REVIEW

**Comment by Schuch666** [comment]
Hello @bakamotokatas Thanks for the contribution!

This looks great! I would like to include all projections but, unfortunately, I don't have time to study, implement and test (I have included some changes that will only affect the automatic tests of the package / cod-cov) all the projections.

Thanks again,
Daniel

**Comment by bakamotokatas** [comment]
@Schuch666, EmissV and Eixport packages help a lot for my master thesis and for a project I'm working on. I can add changes that I have added for myself but may be useful for everyone. Also, I can help you improve these packages.

**Comment by Schuch666** [comment]
Hi @bakamotokatas , all the help is great

Please, check the contribution guidelines: https://github.com/atmoschem/eixport#contributing that has some general guidelines

Can you provide a file (wrfinput or wrfouput) to build an automatic test for Equidistant Cylindrical projection option (to be included to the package automatic tests)

Do you have an Orcid number that you want to include in https://github.com/atmoschem/eixport/blob/master/DESCRIPTION ?

Thank you,
Daniel

**Comment by bakamotokatas** [comment]
Hi @Schuch666,

Thanks for adding me to the description file, my orcid number is 0000-0003-2439-8757. I will check the guidelines.

I added wrfinput file and namelists below.
[wrfinput_example.zip](https://github.com/atmoschem/eixport/files/6743424/wrfinput_example.zip)

**Comment by ibarraespinosa** [comment]
Hello folks!

Suggestion: Run and test on github actions @bakamotokatas
<https://github.com/bakamotokatas>, so that with each commit, GitHub
install eixport and run a specific project like this
https://github.com/atmoschem/vein#1-get-a-project-easier, you would need to
add a workflow like this
https://github.com/atmoschem/vein/blob/master/.github/workflows/brazil_bu.yml
on eixport and here
https://github.com/atmoschem/vein/blob/1e3f6dcf007a36a11ea56ae08998336d95c0f812/.github/workflows/brazil_bu.yml#L74
you can specify the instructions

For instance, you can specify to download a wrfinput, unzip it and then run
eixport on it. If it runs smoothly, the badge would be green.

Em qua., 30 de jun. de 2021 às 16:13, Umur Dinç ***@***.***>
escreveu:

**Pull request merged**
