### PR TITLE
fixed error of incorrect number of dimensions

### PR DESCRIPTION
**Pull request by bakamotokatas**
I got the below error when I used the wrf_raster function.

> Error in inNCLon[, ncol(inNCLon):1] : incorrect number of dimensions

I fixed the error, by removing commas.

### CODE REVIEW

**Comment by ibarraespinosa** [comment]
Oi @Schuch666, tu pode dar uma conferida por favor.

Many thanks @bakamotokatas, we will check this.

**Comment by Schuch666** [comment]
Hello @bakamotokatas 

The wrf_raster expect to read a matrix/array with dimension 2 from a wrf file for latitude and for longitude. In case you are opening a different file or (for some reason) a wrf file with different dimmention of lat / lon it is better not to change for all cases.

Do you have a code/data that generate this error?  I can incorporate these changes for your case 

Thanks,
Daniel

**Comment by Schuch666** [comment]
@bakamotokatas , you can open a new issue (marking me so that I receive the notifications) or use this session (marking me so that I receive the notifications)

**Comment by Schuch666** [comment]
Hi @bakamotokatas check the last version of wrf_raster

**Comment by bakamotokatas** [comment]
Sorry for not answering earlier, I was so busy at the time that I forgot. I checked the final version of wrf_raster and it works fine this time.

But there is another problem that happened last time and I see it is continuing now. Maybe I should also create a new issue for this. wrf_raster is getting the projection of the wrf wrong (seems to reverse longitude and latitude). I think it's probably because my proj or gdal libraries are more up to date. You can see the sample image below. This image actually needs to sit on Turkey.

image

I had created a similar [issue](https://github.com/GIS4WRF/gis4wrf/issues/152) for a similar GIS project. I think it has the same problem. They solved according to this [link](https://github.com/OSGeo/gdal/blob/release/3.0/gdal/MIGRATION_GUIDE.TXT). But I couldn't make any changes in the code for a solution because I don't have much idea about it.

**Pull request closed without merging**
